### ISSUE TITLE
Question: using gup to help maintain a list of globally-installed go packages

### ISSUE THREAD

**Issue by wesley-dean** [nao1215/gup#186]
First, thank you for putting together `gup` and open-sourcing your work.  I appreciate it!

Second, this isn't a bug or a feature request, just a question.  If you're disinclined to respond, please feel free to close this out.  No hard feelings.

My use case is that I have a git repo that includes, among other things, files listing tools that I use that don't come from a system package manager (e.g., apt, dpkg, dnf, etc.).  For example, I have a `requirements.txt` for the Python tools that I use, `package.json` and `package-lock.json` for the Node tools that I use, etc..  I've scripts I can use to quickly install the packages from those files, such as `pip install -r requirements.txt` .]

These all have the commonality that they're not used as modules / dependencies for projects.

I'm looking to accomplish the same thing with go.

I started trying to setup a `go.mod` file and tried to use `go install` but that was a no-go.  Searching around the Internet eventually led me to gup.

I used `gup list` to get a list of the packages and version numbers, so I could use the following to install packages from a file:

```bash
# system 1
gup list > go_packages.txt

# system 2
cat go_packages.txt | sed -Ene 's/[^:]*:\s*//p' | xargs -n1 go install
```

I would keep `go_packages.txt` in the repo and all's right with the world.

I could setup a GitHub Action to do something like:

```yaml

jobs:
  update-go-packages:
    steps:
      - uses: actions/setup-node
      - uses: actions/checkout
      - run: go install github.com/nao1215/gup@latest
      - run: cp go_packages.txt gp_packages.txt.orig && gup update && gup list > go_packages.txt && if diff go_packages.txt go_packages.txt.orig ; then git add go_packages.txt && git commit -m "Bump go stuff" && git push origin "${GITHUB_REF##*/}" ; fi
```
Obviously that's just the quickest cobbled-together-in-an-issue-so-probably-syntactically-garbage thing I thought might convey my thoughts.

So, question is... does this make sense?  am I going down a wrong or stupid path?  do you have any recommendations?

I was originally hoping to use Dependabot with a `go.mod` file but my ignorance of go just wasn't getting me from here to there.  Maybe there's a way to put a `go.mod` file through some `sed` | `xargs` and pass that to `go install` 🤷 

Thank you, again, for your work.  I appreciate your taking the time to read this far and for any advice you may be willing to share.
