### ISSUE TITLE
[Proposal] Add platform testing in the CI (GitHub Actions)

### ISSUE THREAD

**Issue by KEINOS** [nao1215/gup#44]
## What

Add an action for unit-testing on Windows and macOS in the [actions](https://github.com/nao1215/gup/actions).

This allows us to ensure the source can be compiled on most of the platforms (Linux, Win, macOS).

## How

```yaml
name: PlatformTests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_test:
    name: Unit test

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1'
          check-latest: true

      - name: Run unit test
        run: |
          go mod download
          go test -race -v ./...
```
